export const skribblWords = [
  'apple', 'apricot', 'avocado', 'airplane', 'animal', 'astronaut', 'banana', 'boat', 'butterfly', 'basketball', 'beach', 'bird', 'bicycle', 'book', 'bottle',
  'carrot', 'cat', 'cactus', 'computer', 'camera', 'cookie', 'cow', 'cupcake', 'cloud', 'chair', 'cheese', 'chicken', 'crayon', 'clock', 'dolphin',
  'dog', 'donut', 'deer', 'dragon', 'dinosaur', 'desk', 'duck', 'diamond', 'dollar', 'door', 'dress', 'daisy', 'drum', 'elephant', 'egg',
  'fish', 'fire', 'flower', 'frog', 'fan', 'flag', 'football', 'fox', 'feather', 'fork', 'fence', 'fruit', 'guitar', 'grape', 'goat',
  'hat', 'house', 'horse', 'heart', 'hamburger', 'helicopter', 'hammer', 'hockey', 'honey', 'hotdog', 'hourglass', 'ice cream', 'island', 'ink', 'iguana',
  'jellyfish', 'jacket', 'jar', 'jet', 'jester', 'jigsaw', 'juice', 'jungle', 'jump rope', 'kangaroo', 'key', 'kite', 'kiwi', 'koala', 'ketchup',
  'lion', 'lollipop', 'lighthouse', 'leaf', 'laptop', 'lamp', 'lemon', 'lock', 'lobster', 'moon', 'monkey', 'mountain', 'milk', 'motorcycle', 'microphone',
  'nose', 'notebook', 'nurse', 'nest', 'net', 'night', 'nut', 'needle', 'number', 'necklace', 'ninja', 'newspaper', 'ocean', 'octopus', 'owl',
  'panda', 'pineapple', 'pear', 'peach', 'pizza', 'pencil', 'penguin', 'pig', 'pumpkin', 'piano', 'planet', 'potato', 'parrot', 'pyramid', 'paintbrush',
  'queen', 'quilt', 'question', 'quicksand', 'quack', 'quarry', 'quiet', 'quality', 'queue', 'quail', 'quantum', 'quintet', 'quiche', 'quokka', 'quibble',
  'rabbit', 'rainbow', 'robot', 'rose', 'rocket', 'radio', 'rat', 'rhinoceros', 'ring', 'roller coaster', 'rain', 'remote', 'raccoon', 'rug', 'ruler',
  'snake', 'sun', 'star', 'sailboat', 'sandwich', 'sheep', 'shark', 'spider', 'smile', 'socks', 'snowflake', 'snail', 'snowman', 'strawberry', 'submarine',
  'tree', 'train', 'turtle', 'tiger', 'telephone', 'teapot', 'television', 'toilet', 'tomato', 'trombone', 'trampoline', 'triangle', 'turkey', 'taco', 'taxi',
  'umbrella', 'unicorn', 'underwater', 'violin', 'volcano', 'vegetable', 'van', 'vase', 'vampire', 'velvet', 'vacuum', 'vulture', 'vintage', 'vinegar', 'valley', 'village', 'vest', 'view',
  'watermelon', 'whale', 'window', 'watch', 'wheel', 'wagon', 'waffle', 'wreath', 'wolf', 'walrus', 'wizard', 'woodpecker', 'wheat', 'wallet', 'wasabi',
  'xylophone', 'x-ray', 'xenophobia', 'xenon', 'xenial', 'xeriscape', 'xystus', 'xiphoid', 'xeric', 'xenophile', 'xenogenesis', 'xylan', 'xanthophyll', 'xenobiotic', 'xanthan',
  'yacht', 'yak', 'yarn', 'yawn', 'yellow', 'yogurt', 'yoyo', 'yew', 'yolk', 'yacht club', 'yodel', 'yardstick', 'yucca', 'yo-yo',
  'zebra', 'zoo', 'zipper', 'zucchini', 'zigzag', 'zombie', 'zero', 'zodiac', 'zealot', 'zoom', 'zeppelin', 'zither', 'zeitgeist', 'zest', 'zenith'];
